let a = 9;
let b = 7;

console.log("a = ", a);
console.log("b = ", b);
console.log("a + b = ", a + b);
console.log("a + b = ", a + b);

try {
    console.log("a + b = ", a + c);
} catch (err) {
    console.log(`The error is handled. error is >>>> ${err}`)
}

console.log("a + b = ", a + b);
console.log("a + b = ", a + b);
console.log("a + b = ", a + b);
console.log("a + b = ", a + b);
console.log("a + b = ", a + b);
console.log("a + b = ", a + b);
console.log("a + b = ", a + b);
console.log("a + b = ", a + b);

